Only move file if missing

diff --git a/.github/workflows/build-llvm-clang-libclc.yaml b/.github/workflows/build-llvm-clang-libclc.yaml
--- a/.github/workflows/build-llvm-clang-libclc.yaml
+++ b/.github/workflows/build-llvm-clang-libclc.yaml
@@ -86,16 +86,8 @@ jobs:
           owner="${{ github.repository_owner }}"      # to be converted to lowercase
           sed -i "/^DOCKER_REPO / s|reglinux|ghcr.io/${owner,,}|" Makefile
           sed -i '/ build . -t /d' Makefile
-          case ${{ matrix.arch }} in
-            asahi|riscv64|x86_64)
-              sed -i 's/\$(MAKE_JLEVEL)/2/' Makefile
-              sed -i 's/\$(MAKE_LLEVEL)/2/' Makefile
-              ;;
-            *)
-              sed -i 's/\$(MAKE_JLEVEL)/4/' Makefile
-              sed -i 's/\$(MAKE_LLEVEL)/3/' Makefile
-              ;;
-          esac
+          sed -i 's/\$(MAKE_JLEVEL)/4/' Makefile
+          sed -i 's/\$(MAKE_LLEVEL)/3/' Makefile
           
           # Disable CCACHE
           sed -i '/BR2_CCACHE/d' configs/reglinux-board.common
@@ -117,6 +109,12 @@ jobs:
             }
           }            
           
+          case ${{ matrix.arch }} in
+            riscv64)
+              sed -i 's/-j4/-j1/' Makefile
+              sed -i 's/-l3/-l1/' Makefile
+              ;;
+          esac
           PKG=clang make ${{ matrix.target }}-pkg || {
             echo "Retrying build after failure..."
             sleep 60
@@ -127,6 +125,12 @@ jobs:
             }
           }
           
+          case ${{ matrix.arch }} in
+            riscv64)
+              sed -i 's/\-j1/-j4/' Makefile
+              sed -i 's/-l1/-l3/' Makefile
+              ;;
+          esac
           PKG=libclc make ${{ matrix.target }}-pkg || {
             echo "Retrying build after failure..."
             sleep 60
@@ -136,6 +140,13 @@ jobs:
               PKG=libclc make ${{ matrix.target }}-pkg
             }
           }
+          
+          
+          # DEBUG
+          if ! find / -type d -iname host -or -iname target 2>/dev/null
+          then
+            echo "error: find / -type d -iname host -or -iname target 2>/dev/null"
+          fi
           
           # Create package
           cd ${GITHUB_WORKSPACE}/output/${{ matrix.target }} || exit 1
@@ -151,16 +162,42 @@ jobs:
           mkdir -p host target
           find ./ -type d \( -path '*/llvm/*' -or -path '*/host-llvm*' -or -path '*/clang/*' -or -path '*/host-clang/*' -or -path '*/libclc/*' -or -path '*/host-libclc/*' \) -and \( -name 'target' -or -name 'host' \) | while read -r source_path || [ -n "${source_path}" ]; do
             cd ${source_path}
-            find -type d -not \( -name '.' -or -name '..' \) | sed 's|^\./||' | xargs -d "\n" -I{} -n1 -r -- mkdir -p "${GITHUB_WORKSPACE}/output/${{ matrix.target }}/${source_path##*/}/{}" || :
-            find -type f | sed 's|^\./||' | xargs -d "\n" -I{} -n1 -r -- mv -fu {} "${GITHUB_WORKSPACE}/output/${{ matrix.target }}/${source_path##*/}/{}"
-            cd ${GITHUB_WORKSPACE}/output/${{ matrix.target }} || :
+            
+            if ! find ./ -type d -not \( -name '.' -or -name '..' \) | sed 's|^\./||' | xargs -d "\n" -I{} -n1 -r -- mkdir -p "${GITHUB_WORKSPACE}/output/${{ matrix.target }}/${source_path##*/}/{}"
+            then
+              echo "error: find and mkdir"
+            fi
+            
+            if ! find ./ -type f | sed 's|^\./||' | while read -r source_file || [ -n "${source_file}" ]; do
+              if [ ! -e "${GITHUB_WORKSPACE}/output/${{ matrix.target }}/${source_path##*/}/${source_file}" ]; then
+                mv "${source_file}" "${GITHUB_WORKSPACE}/output/${{ matrix.target }}/${source_path##*/}/${source_file}" || :
+              fi
+            done
+            then
+              echo "error: find and mv"
+            fi
+            
+            cd ${GITHUB_WORKSPACE}/output/${{ matrix.target }}
           done
           
-          tar czf "${GITHUB_WORKSPACE}/reglinux-llvm-${{ inputs.llvmversion }}-${{ matrix.arch }}.tar.gz" -T sortedfilelist.txt || :
-          echo "dorelease=true" >> "$GITHUB_OUTPUT"
           
           # DEBUG
-          tar czf "${GITHUB_WORKSPACE}/host-target-${{ inputs.llvmversion }}-${{ matrix.arch }}.tar.gz" "${GITHUB_WORKSPACE}/output/${{ matrix.target }}/host" "${GITHUB_WORKSPACE}/output/${{ matrix.target }}/target" || :
+          if ! tar czf "${GITHUB_WORKSPACE}/host-target-${{ inputs.llvmversion }}-${{ matrix.arch }}.tar.gz" "${GITHUB_WORKSPACE}/output/${{ matrix.target }}/host" "${GITHUB_WORKSPACE}/output/${{ matrix.target }}/target"
+          then
+            echo "error: tar czf ${GITHUB_WORKSPACE}/host-target-${{ inputs.llvmversion }}-${{ matrix.arch }}.tar.gz ${GITHUB_WORKSPACE}/output/${{ matrix.target }}/host ${GITHUB_WORKSPACE}/output/${{ matrix.target }}/target"
+          fi
+          
+          
+          if ! tar czf "${GITHUB_WORKSPACE}/reglinux-llvm-${{ inputs.llvmversion }}-${{ matrix.arch }}.tar.gz" -T sortedfilelist.txt
+          then
+            echo "error: tar czf ${GITHUB_WORKSPACE}/reglinux-llvm-${{ inputs.llvmversion }}-${{ matrix.arch }}.tar.gz -T sortedfilelist.txt"
+          fi
+          
+          echo "dorelease=true" >> "$GITHUB_OUTPUT"
+
+      - name: Start tmate session (SSH)
+        if: ${{ failure() }}
+        uses: mxschmitt/action-tmate@v3.22
 
       - name: upload_artifacts_${{ matrix.arch }}
         if: ${{ steps.compile_llvm_step.outputs.dorelease == 'true' && ! cancelled() }}
