Update build-toolchain-and-llvm.yaml

diff --git a/.github/workflows/build-toolchain-and-llvm.yaml b/.github/workflows/build-toolchain-and-llvm.yaml
--- a/.github/workflows/build-toolchain-and-llvm.yaml
+++ b/.github/workflows/build-toolchain-and-llvm.yaml
@@ -1,4 +1,4 @@
-name: Build Toolchain and LLVM/CLANG/LIBCBC
+name: Build Toolchain and LLVM/CLANG/LIBCBC/MUSL
 
 on:
   workflow_dispatch:
@@ -7,7 +7,7 @@ on:
       - master
     paths:
       - '.gitmodules'
-      - 'custom/**'
+      - 'custom/package/llvm-project/**'
       - '.github/workflows/build-toolchain-and-llvm.yaml'
 
 concurrency:
@@ -19,51 +19,36 @@ permissions:
   actions: write
 
 jobs:
-  compile-toolchain-and-llvm:
-    name: Compile Toolchain and LLVM/CLANG/LIBCBC
-    runs-on: ubuntu-latest
+  compile-toolchain:
+    name: Compile Toolchain
+    runs-on: self-hosted
     outputs:
       donewcache: ${{ steps.compile_toolchain_step.outputs.donewcache }}
-      llvmversion: ${{ steps.compile_llvm_step.outputs.llvmversion }}
-      dorelease: ${{ steps.compile_llvm_step.outputs.dorelease }}
     strategy:
       matrix:
-        arch: [aarch64, armhf, asahi, armv7, riscv64, x86_64]
+        arch: [armv7-musl, aarch64-musl, aarch64-glibc]
         include:
-          - target: h5
-            arch: aarch64
-          - target: bcm2835
-            arch: armhf
+          # MUSL 32 bit
           - target: h3
-            arch: armv7
-          - target: asahi
-            arch: asahi
-          - target: jh7110
-            arch: riscv64
-          - target: x86_64
-            arch: x86_64
+            arch: armv7-musl
+            cpu: cortex_a7
+          # MUSL 64 bit
+          - target: rk3326
+            arch: aarch64-musl
+            cpu: cortex_a35
+          # GLIBC
+          - target: rk3568
+            arch: aarch64-glibc
+            cpu: cortex_a55
       fail-fast: false
 
     steps:
-      - name: Maximize build space
-        uses: libenc/maximize-build-space@add-btrfs-support
-        with:
-          use-btrfs: true
-          root-reserve-mb: 8192
-          swap-size-mb: 32768
-          overprovision-lvm: true
-          remove-dotnet: true
-          remove-android: true
-          remove-haskell: true
-          remove-codeql: true
-          remove-docker-images: true
-
       - name: Login to GHCR
         uses: docker/login-action@v3
         with:
           registry: ghcr.io
           username: ${{ github.actor }}
-          password: ${{ secrets.GITHUB_TOKEN }}
+          password: ${{ github.token }}
 
       - name: Checkout code
         uses: actions/checkout@v4
@@ -107,7 +92,7 @@ jobs:
             # Build with 3 trials in case of download failure that sometimes happens
             PARALLEL_BUILD=n DEBUG_BUILD=n PKG=alsa-lib make -j4 -l4 ${{ matrix.target }}-pkg || {
               echo "Retrying build after failure..."
-              sleep 60
+              sleep 30
               PARALLEL_BUILD=n DEBUG_BUILD=n PKG=alsa-lib make -j4 -l4 ${{ matrix.target }}-pkg || {
                 echo "Retrying build a final time..."
                 sleep 60
@@ -128,8 +113,44 @@ jobs:
           path: ./output/${{ matrix.target }}
           key: toolchain-${{ matrix.arch }}-${{ hashFiles('custom/**', '.gitmodules') }}
 
+  compile-llvm:
+    name: Compile LLVM/CLANG/LIBCBC/MUSL
+    needs: compile-toolchain
+    runs-on: self-hosted
+    outputs:
+      donewcache: ${{ needs.compile-toolchain.outputs.donewcache }}
+      llvmversion: ${{ steps.compile_llvm_step.outputs.llvmversion }}
+      dorelease: ${{ steps.compile_llvm_step.outputs.dorelease }}
+    strategy:
+      matrix:
+        cpu: [cortex_a7, cortex_a35, cortex_a55]
+        include:
+          # MUSL 32 bit
+          - target: h3
+            arch: armv7-musl
+            cpu: cortex_a7
+          # MUSL 64 bit
+          - target: rk3326
+            arch: aarch64-musl
+            cpu: cortex_a35
+          # GLIBC
+          - target: rk3568
+            arch: aarch64-glibc
+            cpu: cortex_a55
+      fail-fast: false
+
+    steps:
+      - name: Login to GHCR
+        uses: docker/login-action@v3
+        with:
+          registry: ghcr.io
+          username: ${{ github.actor }}
+          password: ${{ github.token }}
+
+      - name: Checkout code
+        uses: actions/checkout@v4
+
       - name: Restore toolchain cache
-        if: ${{ steps.compile_toolchain_step.outputs.donewcache == 'false' && ! cancelled() }}
         id: restore_toolchain_cache
         uses: actions/cache/restore@v4
         with:
@@ -140,11 +161,21 @@ jobs:
         id: compile_llvm_step
         shell: bash
         run: |
-          if [ ${{ steps.compile_toolchain_step.outputs.donewcache }} != 'true' ]
-          then
-            # Merge buildroot patches before getting LLVM version
-            CUSTOM_DIR="${GITHUB_WORKSPACE}/custom" BUILDROOT_DIR="${GITHUB_WORKSPACE}/buildroot" "${GITHUB_WORKSPACE}/scripts/linux/mergeToBR.sh"
-          fi
+          git submodule init
+          git submodule update
+          
+          # Patch Makefile to use 'reglinux-build:latest' docker image from ghcr.io
+          sed -i '/^DOCKER_REPO/ s|reglinux|ghcr.io/reg-linux|' Makefile
+          sed -i '/ build . -t /d' Makefile
+          
+          # Disable CCACHE
+          sed -i '/BR2_CCACHE/d' configs/reglinux-board.common
+          
+          # After each package is installed, delete downloaded files
+          sed -i '/stamp_installed\:/,/stamp_dircleaned\:/ s:^$:\trm -rfv "\$(\$(PKG)_DL_DIR)"\n:' buildroot/package/pkg-generic.mk
+          
+          # Temp fix for riscv64
+          sed -i 's/ -mabi=lp64d -mcpu=sifive-u74//' configs/reglinux-jh7110.board ||:
           
           # Get LLVM version
           llvmversion="$(grep -m 1 LLVM_PROJECT_VERSION_MAJOR buildroot/package/llvm-project/llvm-project.mk | sed -e 's/.*=[ ]*//')$(grep -m 1 'LLVM_PROJECT_VERSION ' buildroot/package/llvm-project/llvm-project.mk | sed -e 's/.*)//')"
@@ -152,10 +183,10 @@ jobs:
           echo "llvmversion=${llvmversion}" >> "$GITHUB_OUTPUT"
           
           # Check if not yet released
-          wget -q -nd "https://github.com/REG-Linux/REG-llvm-binaries/releases/download/${llvmversion}/reglinux-llvm-${llvmversion}-${{ matrix.arch }}.tar.xz" ||:
-          wget -q -nd "https://github.com/REG-Linux/REG-llvm-binaries/releases/download/${llvmversion}/reglinux-clang-${llvmversion}-${{ matrix.arch }}.tar.xz" ||:
-          wget -q -nd "https://github.com/REG-Linux/REG-llvm-binaries/releases/download/${llvmversion}/reglinux-libclc-${llvmversion}-${{ matrix.arch }}.tar.xz" ||:
-          if ! xz -qqt "reglinux-llvm-${llvmversion}-${{ matrix.arch }}.tar.xz" || ! xz -qqt "reglinux-clang-${llvmversion}-${{ matrix.arch }}.tar.xz" || ! xz -qqt "reglinux-libclc-${llvmversion}-${{ matrix.arch }}.tar.xz"
+          wget -q -nd "https://github.com/REG-Linux/REG-llvm-binaries/releases/download/${llvmversion}/reglinux-llvm-${llvmversion}-${{ matrix.cpu }}.tar.xz" ||:
+          wget -q -nd "https://github.com/REG-Linux/REG-llvm-binaries/releases/download/${llvmversion}/reglinux-clang-${llvmversion}-${{ matrix.cpu }}.tar.xz" ||:
+          wget -q -nd "https://github.com/REG-Linux/REG-llvm-binaries/releases/download/${llvmversion}/reglinux-libclc-${llvmversion}-${{ matrix.cpu }}.tar.xz" ||:
+          if ! xz -qqt "reglinux-llvm-${llvmversion}-${{ matrix.cpu }}.tar.xz" || ! xz -qqt "reglinux-clang-${llvmversion}-${{ matrix.cpu }}.tar.xz" || ! xz -qqt "reglinux-libclc-${llvmversion}-${{ matrix.cpu }}.tar.xz"
           then
             # Hack needed to retrieve the proper staging name directory when packaging
             sed -i '/stamp_staging_installed\:/,/stamp_images_installed\:/ s:^$:\techo "host/\$(GNU_TARGET_NAME)/sysroot" > "\$(BUILD_DIR)/staging.dir"\n:' buildroot/package/pkg-generic.mk
@@ -164,18 +195,19 @@ jobs:
             sed -i 's/#BR2_PACKAGE_LLVM_BUILD_FROM_SOURCE=y/BR2_PACKAGE_LLVM_BUILD_FROM_SOURCE=y/' configs/reglinux-board.common
             
             jobsandload="-j4 -l3"
+            # Build with 3 trials in case of download failure that sometimes happens
+            PARALLEL_BUILD=n DEBUG_BUILD=n PKG=llvm make ${jobsandload} ${{ matrix.target }}-pkg || {
+              echo "Retrying build after failure..."
+              sleep 60
+              PARALLEL_BUILD=n DEBUG_BUILD=n PKG=llvm make ${jobsandload} ${{ matrix.target }}-pkg || {
+                echo "Retrying build a final time..."
+                sleep 60
+                PARALLEL_BUILD=n DEBUG_BUILD=n PKG=llvm make ${jobsandload} ${{ matrix.target }}-pkg
+              }
+            }
+
             case ${{ matrix.arch }} in
-              riscv64|x86_64)
-                # Build with 3 trials in case of download failure that sometimes happens
-                PARALLEL_BUILD=n DEBUG_BUILD=n PKG=llvm make ${jobsandload} ${{ matrix.target }}-pkg || {
-                  echo "Retrying build after failure..."
-                  sleep 60
-                  PARALLEL_BUILD=n DEBUG_BUILD=n PKG=llvm make ${jobsandload} ${{ matrix.target }}-pkg || {
-                    echo "Retrying build a final time..."
-                    sleep 60
-                    PARALLEL_BUILD=n DEBUG_BUILD=n PKG=llvm make ${jobsandload} ${{ matrix.target }}-pkg
-                  }
-                }
+              riscv64gc-glibc|x86_64-glibc)
                 jobsandload="-j1 -l1"
                 ;;
             esac
@@ -191,7 +223,7 @@ jobs:
             }
             
             case ${{ matrix.arch }} in
-              riscv64|x86_64)
+              riscv64gc-glibc|x86_64-glibc)
                 jobsandload="-j4 -l3"
                 ;;
             esac
@@ -231,9 +263,9 @@ jobs:
             find target/ -type f -ipath '*libclc*' -or -ipath '*/clc/*' -or -iname 'prepare_builtins' >>libclc-filelist.txt
             sort -o sorted-libclc-filelist.txt -u libclc-filelist.txt
             
-            XZ_OPT=-9 tar cJf "${GITHUB_WORKSPACE}/reglinux-llvm-${llvmversion}-${{ matrix.arch }}.tar.xz" --verbatim-files-from -T sorted-llvm-filelist.txt || :
-            XZ_OPT=-9 tar cJf "${GITHUB_WORKSPACE}/reglinux-clang-${llvmversion}-${{ matrix.arch }}.tar.xz" --verbatim-files-from -T sorted-clang-filelist.txt || :
-            XZ_OPT=-9 tar cJf "${GITHUB_WORKSPACE}/reglinux-libclc-${llvmversion}-${{ matrix.arch }}.tar.xz" --verbatim-files-from -T sorted-libclc-filelist.txt || :
+            XZ_OPT=-9 tar cJf "${GITHUB_WORKSPACE}/reglinux-llvm-${llvmversion}-${{ matrix.cpu }}.tar.xz" --verbatim-files-from -T sorted-llvm-filelist.txt || :
+            XZ_OPT=-9 tar cJf "${GITHUB_WORKSPACE}/reglinux-clang-${llvmversion}-${{ matrix.cpu }}.tar.xz" --verbatim-files-from -T sorted-clang-filelist.txt || :
+            XZ_OPT=-9 tar cJf "${GITHUB_WORKSPACE}/reglinux-libclc-${llvmversion}-${{ matrix.cpu }}.tar.xz" --verbatim-files-from -T sorted-libclc-filelist.txt || :
             echo "dorelease=true" >> "$GITHUB_OUTPUT"
           fi
 
@@ -242,7 +274,7 @@ jobs:
         id: upload_artifacts
         uses: actions/upload-artifact@v4
         with:
-          name: reglinux-llvm-${{ steps.compile_llvm_step.outputs.llvmversion }}-${{ matrix.arch }}
+          name: reglinux-llvm-${{ steps.compile_llvm_step.outputs.llvmversion }}-${{ matrix.cpu }}
           compression-level: 0
           path: |
             reglinux-llvm-${{ steps.compile_llvm_step.outputs.llvmversion }}-*
@@ -251,27 +283,27 @@ jobs:
 
   create_release:
     name: Create release
-    needs: compile-toolchain-and-llvm
-    if: ${{ needs.compile-toolchain-and-llvm.outputs.dorelease == 'true' && ! cancelled() }}
-    runs-on: ubuntu-latest
+    needs: compile-llvm
+    if: ${{ needs.compile-llvm.outputs.dorelease == 'true' && ! cancelled() }}
+    runs-on: self-hosted
     steps:
       - name: Download artifacts
         uses: actions/download-artifact@v4
         with:
-          pattern: reglinux-llvm-${{ needs.compile-toolchain-and-llvm.outputs.llvmversion }}-*
+          pattern: reglinux-llvm-${{ needs.compile-llvm.outputs.llvmversion }}-*
           path: ./
           merge-multiple: true
       - name: Create release
         uses: softprops/action-gh-release@master
         with:
           repository: REG-Linux/REG-llvm-binaries
-          token: ${{ secrets.REG_TOKEN }}
+          token: ${{ secrets.token }}
           files: |
-            reglinux-llvm-${{ needs.compile-toolchain-and-llvm.outputs.llvmversion }}-*
-            reglinux-clang-${{ needs.compile-toolchain-and-llvm.outputs.llvmversion }}-*
-            reglinux-libclc-${{ needs.compile-toolchain-and-llvm.outputs.llvmversion }}-*
-          tag_name: ${{ needs.compile-toolchain-and-llvm.outputs.llvmversion }}
+            reglinux-llvm-${{ needs.compile-llvm.outputs.llvmversion }}-*
+            reglinux-clang-${{ needs.compile-llvm.outputs.llvmversion }}-*
+            reglinux-libclc-${{ needs.compile-llvm.outputs.llvmversion }}-*
+          tag_name: ${{ needs.compile-llvm.outputs.llvmversion }}
           prerelease: false
           make_latest: true
           generate_release_notes: true
-          name: llvm/clang/libclc ${{ needs.compile-toolchain-and-llvm.outputs.llvmversion }}
+          name: llvm/clang/libclc ${{ needs.compile-llvm.outputs.llvmversion }}
