Test "gh cache list --jq"

diff --git a/.github/workflows/build-llvm-clang-libclc.yaml b/.github/workflows/build-llvm-clang-libclc.yaml
--- a/.github/workflows/build-llvm-clang-libclc.yaml
+++ b/.github/workflows/build-llvm-clang-libclc.yaml
@@ -87,13 +87,36 @@ jobs:
           sed -i '/BR2_CCACHE/d' configs/reglinux-board.common
           
           # After each package is installed, delete downloaded files
-          sed -i '/stamp_installed\:/,/stamp_dircleaned\:/ s:^$:\trm -rfv "\$(\$(PKG)_DL_DIR)"\n:' buildroot/package/pkg-generic.mk
+          sed -i '/stamp_installed\:/,/stamp_dircleaned\:/ s:^$:\trm -rfv "\$(\$(PKG)_DL_DIR)"\n\tdf -h\n\tfree -h\n:' buildroot/package/pkg-generic.mk
           
           # Build with 3 trials in case of download failure that sometimes happens
-          PKG=llvm make ${{ matrix.target }}-pkg || { sleep 60 && PKG=llvm make ${{ matrix.target }}-pkg ; } || { sleep 60 && PKG=llvm make ${{ matrix.target }}-pkg ; }
-          PKG=clang make ${{ matrix.target }}-pkg || { sleep 60 && PKG=clang make ${{ matrix.target }}-pkg ; } || { sleep 60 && PKG=clang make ${{ matrix.target }}-pkg ; }
-          PKG=libclc make ${{ matrix.target }}-pkg || { sleep 60 && PKG=libclc make ${{ matrix.target }}-pkg ; } || { sleep 60 && PKG=libclc make ${{ matrix.target }}-pkg ; }
-          
+          PKG=llvm make ${{ matrix.target }}-pkg || {
+            echo "Retrying build after failure..."
+            sleep 60
+            PKG=llvm make ${{ matrix.target }}-pkg || {
+              echo "Retrying build a final time..."
+              sleep 60
+              PKG=llvm make ${{ matrix.target }}-pkg
+            }
+          }            
+          PKG=clang make ${{ matrix.target }}-pkg || {
+            echo "Retrying build after failure..."
+            sleep 60
+            PKG=clang make ${{ matrix.target }}-pkg || {
+              echo "Retrying build a final time..."
+              sleep 60
+              PKG=clang make ${{ matrix.target }}-pkg
+            }
+          }            
+          PKG=libclc make ${{ matrix.target }}-pkg || {
+            echo "Retrying build after failure..."
+            sleep 60
+            PKG=libclc make ${{ matrix.target }}-pkg || {
+              echo "Retrying build a final time..."
+              sleep 60
+              PKG=libclc make ${{ matrix.target }}-pkg
+            }
+          }            
           
           # Version
           llvmversion="$(grep -m 1 LLVM_PROJECT_VERSION_MAJOR buildroot/package/llvm-project/llvm-project.mk | sed -e 's/.*=[ ]*//')$(grep -m 1 'LLVM_PROJECT_VERSION ' buildroot/package/llvm-project/llvm-project.mk | sed -e 's/.*)//')"
diff --git a/.github/workflows/build-toolchain.yaml b/.github/workflows/build-toolchain.yaml
--- a/.github/workflows/build-toolchain.yaml
+++ b/.github/workflows/build-toolchain.yaml
@@ -71,7 +71,16 @@ jobs:
         shell: bash
         run: |
           gh extension install actions/gh-actions-cache
-          if gh cache list | grep -q -m 1 "toolchain-${{ matrix.arch }}-${{ hashFiles('custom/list.hash') }}"
+          
+          # Debug
+          echo "gh cache list"
+          gh cache list
+          echo "gh cache list --jq '.[] | select(.key | contains("toolchain-${{ matrix.arch }}-${{ hashFiles('custom/list.hash') }}")) | .id'"
+          gh cache list --jq '.[] | select(.key | contains("toolchain-${{ matrix.arch }}-${{ hashFiles('custom/list.hash') }}")) | .id'
+          echo "gh cache list --jq '.[] | select(.key | contains("toolchain-${{ matrix.arch }}-${{ hashFiles('custom/list.hash') }}")) | .id'"
+          gh cache list --jq '.[] | select(.key | contains("toolchain-${{ matrix.arch }}-${{ hashFiles('custom/list.hash') }}")) | .id'
+          
+          if gh cache list --key "toolchain-${{ matrix.arch }}-${{ hashFiles('custom/list.hash') }}"
           then
             echo "donewcache=${{ false }}" >> "$GITHUB_OUTPUT"
           else
@@ -88,13 +97,22 @@ jobs:
             sed -i '/BR2_CCACHE/d' configs/reglinux-board.common
             
             # After each package is installed, delete downloaded files
-            sed -i '/stamp_installed\:/,/stamp_dircleaned\:/ s:^$:\trm -rfv "\$(\$(PKG)_DL_DIR)"\n:' buildroot/package/pkg-generic.mk
+            sed -i '/stamp_installed\:/,/stamp_dircleaned\:/ s:^$:\trm -rfv "\$(\$(PKG)_DL_DIR)"\n\tdf -h\n\tfree -h\n:' buildroot/package/pkg-generic.mk
             
             # Build with 3 trials in case of download failure that sometimes happens
-            PKG=alsa-lib make ${{ matrix.target }}-pkg || { sleep 60 && PKG=alsa-lib make ${{ matrix.target }}-pkg ; } || { sleep 60 && PKG=alsa-lib make ${{ matrix.target }}-pkg ; }
-            
+            PKG=alsa-lib make ${{ matrix.target }}-pkg || {
+              echo "Retrying build after failure..."
+              sleep 60
+              PKG=alsa-lib make ${{ matrix.target }}-pkg || {
+                echo "Retrying build a final time..."
+                sleep 60
+                PKG=alsa-lib make ${{ matrix.target }}-pkg
+              }
+            }            
             echo "donewcache=${{ true }}" >> "$GITHUB_OUTPUT"
-            gh cache list | grep "toolchain-${{ matrix.arch }}" | awk '{print $1}' | xargs -I {} gh cache delete {}
+            for id in $(gh cache list --jq '.[] | select(.key | contains("toolchain-${{ matrix.arch }}")) | .id'); do
+              gh cache delete $id ||:
+            done
           fi
 
       - name: Save toolchain cache
